version: "3.9"

services:
  app:
    image: node:17-alpine
    container_name: blog
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 3000:3000
    command: >
      sh -c "
        npm install &&
        npm run start
      "
